# CircleCi configuration version
version: 2

jobs:
  build:
    docker:
      # specific environment version to avoid incompatible updates
      - image: bitriseio/docker-android:v2017_09_09-06_45-b744

    working_directory: ~/workspace

    steps:

      - run:
          name: Lists installed targets
          command: android list target
          environment:
            TERM: dumb

      - run:
          name: List available targets and other sdk modules
          command: sdkmanager --list --include_obsolete --verbose
          environment:
            TERM: dumb

      - run:
          name: Install custom system image
          command: sdkmanager "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Create avd
          command: echo no | avdmanager create avd -n testEmulator -k "system-images;android-23;google_apis;armeabi-v7a"
          environment:
            TERM: dumb

      - run:
          name: Start emulator
          command: emulator -avd testEmulator
          environment:
            TERM: dumb

      - checkout

      - run:
          name: Unit testing
          command: ./gradlew test
          environment:
            TERM: dumb

      - run:
          name: Instrumentation testing
          command: ./gradlew connectedCheck
          environment:
            TERM: dumb