version: 2

jobs:
  build:
    docker:
      - image: bitriseio/docker-android

    working_directory: ~/workspace

    steps:
      - run:
          name: Install Missing v23 Emulator
          command: sdkmanager "system-images;android-23;default;x86" --verbose
          environment:
            TERM: dumb

      - run:
          name: Show targets
          command: android list targets
          environment:
            TERM: dumb

      - run:
          name: Create Emulator
          command: echo no | android create avd -n testAVD -t $(android list targets | grep android-23 | cut -d" " -f2) --abi google_apis/armeabi-v7a
          environment:
            TERM: dumb

      - run:
          name: Start Emulator
          command: emulator -avd testAVD
          environment:
            TERM: dumb

      - checkout

      - run:
          name: Unit Test
          command: ./gradlew test
          environment:
            TERM: dumb

      - run:
          name: Instrumentation Test
          command: ./gradlew connectedCheck
          environment:
            TERM: dumb